[project]
name = "FicImageScript"
version = "5.0.0"
authors = [
    { name = "Emmanuel C. Jemeni", email = "jemenichinonso11@gmail.com" },
]
description = "FicImage is an application designed to enhance the reading experience of FicHub files."
readme = "PYPI_README.rst"
requires-python = ">=3.12"
license = "MIT"
license-files = ["LICENSE"]
keywords = ["fanfiction", "fichub", "ficimage", "image", "epub", "html", "zip"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Topic :: Internet :: WWW/HTTP",
    "Environment :: Console",
    "Natural Language :: English",
]
dependencies = [
    "beautifulsoup4>=4.15.0",
    "ebooklib>=0.20",
    "httpx>=0.28.1",
    "lxml>=6.1.1",
    "packaging>=26.2",
    "pillow>=12.2.0",
]

[project.scripts]
ficimage = "ficimagescript.main:main"

[project.urls]
"Homepage" = "https://github.com/Jemeni11/FicImage"
"Bug Tracker" = "https://github.com/Jemeni11/FicImage/issues"
"Changelog" = "https://github.com/Jemeni11/FicImage/blob/main/CHANGELOG.md"
"Funding" = "https://buymeacoffee.com/jemeni11"

[build-system]
requires = ["uv_build>=0.11.23,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = ["ruff>=0.15.19", "ty>=0.0.53"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = [
    "F",    # Pyflakes rules
    "W",    # PyCodeStyle warnings
    "E",    # PyCodeStyle errors
    "I",    # Sort imports properly
    "UP",   # Warn if certain things can changed due to newer Python versions
    "C4",   # Catch incorrect use of comprehensions, dict, list, etc
    "ISC",  # Good use of string concatenation
    "ICN",  # Use common import conventions
    "RET",  # Good return practices
    "SIM",  # Common simplification rules
    "TID",  # Some good import practices
    "TC",   # Enforce importing certain types in a TYPE_CHECKING block
    "PTH",  # Use pathlib instead of os.path
    "TD",   # Be diligent with TODO comments
    "FURB", # Suggest more idiomatic Python patterns
    "B",    # https://docs.astral.sh/ruff/rules/#flake8-bugbear-b
]

[tool.ty.rules]
unresolved-import = "warn"
