name: ficimage
summary: FicImage is an application designed to enhance the reading experience of FicHub epubs.
description: |
     FicImage is an application designed to enhance the reading experience of FicHub epubs. With FicImage, 
     users can easily add missing images to their FicHub epubs, bringing the stories to life with vibrant
     visuals. This user-friendly tool allows readers to fully immerse themselves in their favourite fan 
     fiction stories and enjoy them in a whole new way.
version: 3.0.0
base: core22
confinement: strict

parts:
  ficimage:
    plugin: python
    source: .
    # stage-packages:
    #    - python3-usb

apps:
  ficimage:
    command: FicImage/main
    # plugs:
    #   - raw-usb
    #   - hardware-observe
